[package]
name = "gll-dart"
version = "0.1.0"
authors = ["Ana-Maria <mihalacheana.maria@yahoo.com>"]
repository = "https://github.com/lykenware/gll"
license = "MIT/Apache-2.0"
description = "Dart GLL grammar."

[[bin]]
doc = false
name = "dump-ast"
test = false

[lib]
doctest = false

[dependencies]
gll = { path = ".." }

[build-dependencies]
gll = { path = ".." }

